backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "voitures"
    label: "Catalogue Voitures"
    folder: "voitures"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nom", name: "nom", widget: "string" }
      - { label: "Marque", name: "marque", widget: "string" }
      - { label: "Année", name: "annee", widget: "number" }
      - { label: "Prix (€)", name: "prix", widget: "number" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
